### ISSUE TITLE
how do i check for consent on each item?

### ISSUE THREAD

**Issue by Photogad** [DavidEdwards/GDPRConsent#10]
sorry just a quick question.

I tried it this way which seems right, but it didn't work:

```
        if (ConsentHelper.hasConsent("FIREBASE_CRASH"))
        {
            Log.wtf("hello","HAS CONSENT!");
        } else {
            Log.wtf("hello","consent not found");
        }
```

**Comment by DavidEdwards** [comment]
Where did you run that command? 

If you run that command before you have used one of the "show" methods, then you need to manually populate the values.

See here as an example:

https://github.com/DavidEdwards/GDPRConsent/blob/master/app/src/main/java/dae/gdprtest/App.kt

**Comment by DavidEdwards** [comment]
Please post again if this is still an issue.
