### ISSUE TITLE
"Visit page" button doesn't open URL

### ISSUE THREAD

**Issue by tmk13** [DavidEdwards/GDPRConsent#11]
Clicking "Visit page" button has no effect because in OnClickListener of moreInformationButton it has to be:
``
val url = URL(request.what)
``
instead of:
``
val url = URL(request.moreInformation)
``

**Comment by DavidEdwards** [comment]
I don't understand the issue.

"What" and "More Information" are two different sections of information.

More Information is used to link to an external source (if it is a URL).

![device-2018-06-04-100037](https://user-images.githubusercontent.com/1585923/40905621-cf6a4b40-67de-11e8-9b9f-9f3a61a5c53f.png)

And in the library code. You can see that the button is identified as more information, and so is the data source.

```kotlin
binding.moreInformationButton.setOnClickListener {
    try {
        val url = URL(request.moreInformation)

        val intent = Intent(Intent.ACTION_VIEW)
        intent.data = Uri.parse(url.toURI().toString())
        startActivity(intent)
    } catch (e: MalformedURLException) {
        // No URL? No problem. It must just be standard text.
    } catch (e: ActivityNotFoundException) {
        e.printStackTrace()
        // This should be handled better. The device has no facility to display web pages.
    }
}
```

I will close this, but if you feel like I've misunderstood, feel free to open it again with more information about what you mean.
