### ISSUE TITLE
IAB Europe Framework support

### ISSUE THREAD

**Issue by Waschnick** [DavidEdwards/GDPRConsent#13]
Are you plannig to support the IAB Europe Transparency & Consent Framework? [Mobile specs](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Mobile%20In-App%20Consent%20APIs%20v1.0%20Draft%20for%20Public%20Comment.md).

**Comment by DavidEdwards** [comment]
No immediate plans. I was considering making it possible for developers to create a custom screen to display for use with the consent request system. So that a more complex view can be shown.

Am I correct in my reading of that framework, that the purpose is to standardize consenting a list of accessors of personal data for advertising purposes?

For example, you have AdMob, and consenting a list of individual ad publishers that they share personal data with.

**Comment by Waschnick** [comment]
It's more about standardize the way the consent can be requested by vendors/libs. They defined a stanard object which contains purposes for a more detailed opt-in/opt-out. Addionally the framework contains policies and a set of purposes.

So if a vendor like AdMob supports the IAB framework and your app has a CMP (which means a consent requesting tool which supports the IAB Framework) the vendor (AdMob) will respect the settings and will pull the current consent state from that CMP.

It's actually more designed for the web, not for apps.

**Comment by Waschnick** [comment]
Which brings me to a question: Is it possible to have an invisible WebView, which for example uses a central domain with the IAB Cookie and by doing this share the cookie between the app and the web? And between multiple apps, as they would use the same central domain.

So for example if the user uses chrome on his mobile, gives consent for exampe for website-1.com. Next he uses the app of website-1 and the app does not need to collect the consent, as it can read the cookie from the website?

**Comment by DavidEdwards** [comment]
Cookies are typically client side, if you had some kind of synchronizing mechanism that would be fine. 

For example, if you have a unique ID stored in your cookies on all devices from website-1.com, you can use that unique ID to access the "real" cookie information on website-1.com. 

This would likely require some kind of login system, making the idea harder to realize.

**Comment by Waschnick** [comment]
Nah, on one device it would work. The question is: Does Chrome (or Safari for iOS) and the WebView in apps share the same cookie?

**Comment by DavidEdwards** [comment]
They are sandboxed to your App.

See this for example, this exists inside one of my Apps:

![image](https://user-images.githubusercontent.com/1585923/41103945-a128b148-6a6a-11e8-8f40-dab24d7ca47f.png)

Note the "Cookies" file. That contains the cookies from the WebView.

**Comment by DavidEdwards** [comment]
Closing this due to activity.
