### ISSUE TITLE
how to change the purple color of the slider and the arrows

### ISSUE THREAD

**Issue by Photogad** [DavidEdwards/GDPRConsent#15]
ok this is probably a dumb question because i am a beginner developer but how to change the purple color of the slider and the arrows?  i want it to match more of the theme of my app.

According to your theme.xml file it should be taking the color from my colorPrimary, but it's not.

**Comment by DavidEdwards** [comment]
Sorry to reply so late, you should be able to change the colours with these values:

```
    <color name="colorGdprPrimary">#FFFFFF</color>
    <color name="colorGdprPrimaryDark">#FFFFFF</color>
    <color name="colorGdprAccent">#D81B60</color>
```

Source: https://github.com/DavidEdwards/GDPRConsent/blob/master/library/src/main/res/values/colors.xml
