### ISSUE TITLE
ERROR: Failed to resolve: com.github.DavidEdwards:GDPRConsent:1.0

### ISSUE THREAD

**Issue by OrWestSide** [DavidEdwards/GDPRConsent#17]
Followed the steps in README.md per letter. Still I get this error:
**ERROR: Failed to resolve: com.github.DavidEdwards:GDPRConsent:1.0**

I added `url 'https://jitpack.io'` in `maven`, added the extra dependencies in the gradle.build, added the complie options and data binding in `android` and the classpath as instructed, but I get this error.

```
ERROR: Failed to resolve: com.github.DavidEdwards:GDPRConsent:1.0
Show in Project Structure dialog
Affected Modules: MyApplication-app
```

Any ideas about what is going on?

**Comment by DavidEdwards** [comment]
The latest version is 1.0.3, have you tried that?

https://github.com/DavidEdwards/GDPRConsent/releases/tag/1.0.3

**Comment by OrWestSide** [comment]
Looks like I used `https://jitpack.io` only at the `buildscript` and not at `allprojects` block. Solved
