### ISSUE TITLE
App theme replaced after adding the library

### ISSUE THREAD

**Issue by rosenpin** [DavidEdwards/GDPRConsent#4]
That's a very weird issue, but after implementing the library in my app my app theme was changed, specifically the colors, the primary color/accent color was changed to white/pink.

For some reasone my @style/AppTheme was changed to point to your apptheme, that uses the GDPRAccentColor etc.

After updating the build tools to the alpha14 as you recommended
`classpath 'com.android.tools.build:gradle:3.2.0-alpha14'`
When checking where apptheme pointed to in the manifest it shows my theme correctly, but after building and running it still uses the pink/white theme.

**Comment by DavidEdwards** [comment]
Could you change to version 0.9?

That should help. I didn't update the read me.

0.8 writes it's theme in the application manifest tag.

**Comment by rosenpin** [comment]
Cool, thanks
