### ISSUE TITLE
False positive for RESULT_OK on activity result

### ISSUE THREAD

**Issue by rosenpin** [DavidEdwards/GDPRConsent#5]
In the consent activity, when pressing the back button and going back to the app, the onactivityresult always returns resultCode == RESULT_OK

So even if the user quits the consent activity and presses the back button, the result will always be OK

**Comment by DavidEdwards** [comment]
It should only return cancelled to the app when the user presses back and there is a required item that isn't consented to.

That indicates to the main app that the user cannot use the app, due to the missing consent.

**Comment by rosenpin** [comment]
That's kind of misleading then.
Anyway, what if I want to save a preference for when the user completes the GDPR thing so I won't show it again?
I saw the showGdprOnlyNew method but it seems like it loads the activity and then kills it, which is a pretty bad behaviour as it's pretty visible. It's not something I can show to the user every time my app loads.

So say I only want the consent activity to show up once or until the user goes through it. Is there a way to do this?

**Comment by DavidEdwards** [comment]
I could make a method to test whether the activity needs to be loaded.

That would be a better user experience.

At the moment there is no such function. In my apps there's no noticeable
transition between the activities.

It was my intention to use 'showGdprOnlyNew' for every start. I can
understand how that would be undesirable. 

I'll see what I can do today.

**Comment by rosenpin** [comment]
Appreciated, thanks for the library BTW.
It's super helpful especially because I don't have much time to work on my apps now, nice of you to open source it :)

**Comment by DavidEdwards** [comment]
@rosenpin Please try version `0.9.1`.

New function:

```
if(ConsentHelper.hasNewOrRequired(this, list)) {
    ConsentHelper.showGdprOnlyNew(this, RC_CONSENT, list)
}
```

**Comment by rosenpin** [comment]
Nice
