### ISSUE TITLE
Missing project build.gradle and other configuration files to build the project

### ISSUE THREAD

**Issue by rosenpin** [DavidEdwards/GDPRConsent#6]
Seems like you didn't push the build.gradle and other config files needed to compile the project, I want to send a PR and improve the library but I can't do that if I can't build the project.

**Comment by rosenpin** [comment]
Actually, it seems like you actually split the project into 2 projects. Why would you do that?
You can put 2 modules (for example the library and the example) under the same project, it also makes it easier to build and test.
Not to mention easier to manage, send/receive PRs etc.
You can check out an example here:
https://github.com/rosenpin/FadingTextView
Where the library module is called fadingtextview and the example is called app.

In its current state it's kind of a pain to build, test and contribute to your library

**Comment by rosenpin** [comment]
Oh and by the way, the library project failes to build with this error message:
`GDPRConsent/library/app/keystore.gradle (No such file or directory)`

**Comment by DavidEdwards** [comment]
That file is for uploading to bintray. I might remove the whole thing and use GitHub as repository.

Other gradle files should be there. I'll have a look today, hopefully.

**Comment by DavidEdwards** [comment]
So! It now uses jitpack to pull from Github. No more bintray dependencies.

It also sits as one project with two modules, as you suggested. That works well. Thank you for the suggestion.

**Comment by rosenpin** [comment]
Great!
Thanks :)
